---
- hosts: all
  vars:
    - sdk_root: "/opt/Espressif/"
    - nodemcu_root: "/opt/NodeMCU/"
    - nodemcu_env:
        path: "$PATH:{{ sdk_root }}/xtensa-lx106-elf/bin/"

  tasks:
    - name: update apt cache
      sudo: true
      apt: update_cache=yes

    - name: install deps
      sudo: true
      apt: name={{ item }} state=present
      with_items: [make, unrar-free, autoconf, automake, libtool, gcc, g++,
                   gperf, flex, bison, texinfo, gawk, ncurses-dev,
                   libexpat-dev, python, python-serial, sed, git, unzip]

    - name: crate directories
      sudo: true
      file: dest={{ item }} mode=0777 state=directory
      with_items: ["{{ sdk_root }}", "{{ nodemcu_root }}"]

    - name: clone esp-open-sdk
      git:
        repo: https://github.com/pfalcon/esp-open-sdk.git
        force: yes
        dest: "{{ sdk_root }}"
        recursive: yes

    - name: build esp-open-sdk
      shell: "cd {{ sdk_root }} && make STANDALONE=y"

    - name: clone nodemcu-firmware
      git:
        repo: https://github.com/nodemcu/nodemcu-firmware.git
        force: yes
        dest: "{{ nodemcu_root }}"

    - name: build nodemcu-firmware
      environment: nodemcu_env
      shell: "cd {{ nodemcu_root }} && make"
